[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "robot_arm"
version = "0.1.0"
description = "Personal control code and experiments for an SO-101 follower arm using LeRobot."
requires-python = ">=3.12"
dependencies = [
    "lerobot[feetech, smolvla]",
    "pytest",
    "mujoco",
    "gymnasium",
    "numpy",
    "stable-baselines3",
    "hydra-core",
]

[tool.setuptools.packages.find]
where = ["src"]
