temporary_dir = "outputs/temp"

[[policies]]
name = "VLA"
url = "https://drive.google.com/file/d/1RnYFMlAvIGsnJnsU6TtI_L-aEO0iDEGl/view?usp=sharing"
sha256 = "572379e37f6d544c5d88c5a987c49397a7b0f8f888eaaa76863f468c34f658f9"
archive = "vla_2026-09-21_09-29-43.zip"
archive_root = "runpod_2026-09-21_09-29-43"
destination = "outputs/train_vla/runpod_2026-09-21_09-29-43"
required_files = [
    "checkpoints/last/pretrained_model/model.safetensors",
    "checkpoints/last/pretrained_model/config.json",
    "checkpoints/last/pretrained_model/policy_preprocessor.json",
    "checkpoints/last/pretrained_model/policy_postprocessor.json",
    "checkpoints/last/pretrained_model/policy_preprocessor_step_5_normalizer_processor.safetensors",
    "checkpoints/last/pretrained_model/policy_postprocessor_step_0_unnormalizer_processor.safetensors",
]

[[policies]]
name = "Joint controller"
url = "https://drive.google.com/file/d/10dWnLcdE1nC3IHoxLa0oA0edLcSV9d9l/view?usp=sharing"
sha256 = "d736ef0f442ca2660c3257c06d7be9dd3c5e2b2fc98b592f018ef4fab7eaf128"
archive = "joint_policy_2026-09-21_08-22-20.zip"
archive_root = "2026-09-21/08-22-20"
destination = "outputs/train_joint_policy/2026-09-21/08-22-20"
required_files = [
    "checkpoints/jax_sac_final_1000464.pkl",
    "checkpoints/jax_sac_final_1000464.actor.npz",
    ".hydra/config.yaml",
    "model/scene.xml",
    "model/so101.xml",
]
