num_workers: 10
detailed_metrics: true
pose_delta_diagnostics_enabled: true
sync_weights_every_n_cartesian_actions: 1
broadcast_weights_every_n_steps: 1000
total_training_steps: 30000
learning_rate: 0.0003
actor_forward_loss_weight: 0.1
critic_forward_loss_weight: 0.1
buffer_size: 100000
real_data:
  episode_paths: []
  buffer_size: 10000
  fraction: 0.0
learning_starts: 5000
batch_size: 1024
gamma: 1.0
terminate_at_cartesian_action_end: true
tau: 0.005
train_freq: 10
gradient_steps: 10
save_episodes_freq: 20
checkpoint_every_n_steps: 10000
worker_check_seconds: 30
gpu_sample_seconds: 3
