import os
import time
import numpy as np

import hydra
from omegaconf import DictConfig
from hydra.core.hydra_config import HydraConfig

from robot_arm.sim_arm import SimArm
from robot_arm.env import RobotEnv
from robot_arm.high_level_control_wrapper import HighLevelControlWrapper
from robot_arm.recorder import EpisodeRecorder

@hydra.main(version_base=None, config_path="../conf", config_name="config")
def record_synthetic_episode(cfg: DictConfig):
    # 1. Initialize backend
    print("Initializing SimArm...")
    arm = SimArm(
        model_path=cfg.model_path, 
        height=cfg.camera.height, 
        width=cfg.camera.width
    )

    # 2. Track steps for this trajectory
    env = RobotEnv(
        arm=arm, 
        max_steps=cfg.max_steps, 
        height=cfg.camera.height, 
        width=cfg.camera.width
    )

    env = HighLevelControlWrapper(
        env=env,
        high_level_hz=cfg.frequencies.high_level,
        low_level_hz=cfg.frequencies.low_level
    )

    # 3. Setup trajectory: now we generate a linear trajectory of absolute high-level targets.
    start_pos = np.zeros(6, dtype=np.float32)
    end_pos = np.array([0.5, 0.5, -0.5, 0.0, 0.0, 0.2], dtype=np.float32)
    
    trajectory = np.linspace(start_pos, end_pos, cfg.max_steps)

    # 4. Initialize recorder inside Hydra's output directory
    hydra_cfg = HydraConfig.get()
    output_dir = os.path.join(hydra_cfg.runtime.output_dir, "recordings")
    
    obs, info = env.reset()
    recorder = EpisodeRecorder(
        output_dir=output_dir, 
        jpeg_quality=cfg.camera.jpeg_quality,
        episode_name="synthetic_01"
    )
    
    print(f"Executing trajectory and recording to {output_dir}...")
    
    # 5. Execute and record loop
    for step_idx in range(cfg.max_steps):
        # High level action is an absolute position target
        action = trajectory[step_idx]
        
        obs, reward, terminated, truncated, info = env.step(action)
        
        # Record the observation AFTER the step, pairing it with the dense 
        # trajectory that was generated by the environment taking this high-level action.
        recorder.step(step_idx, obs, action, reward=reward, info=info)
        
        if terminated or truncated:
            break
            
    # Save the episode metadata
    recorder.save()
    print("Recording complete.")

if __name__ == "__main__":
    record_synthetic_episode()
